import { PolicyLayout, PolicySection, PolicyHeading, PolicySubHeading } from '../components/PolicyComponents';

export const metadata = {
  title: 'Privacy Policy — Buggy Basket',
  description: 'Privacy Policy for Buggy Basket.',
};

export default function PrivacyPage() {
  return (
    <PolicyLayout
      title="Privacy Policy"
      lastUpdated="March 29, 2026"
      warning="This is a draft Privacy Policy generated by FreePrivacyPolicy. Please review and replace with final legal text approved by the team/lawyer before going live."
      tocItems={[
        'Interpretation and Definitions',
        'Collecting and Using Your Personal Data',
        'Disclosure of Your Personal Data',
        'Security of Your Personal Data',
        "Children's Privacy",
        'Links to Other Websites',
        'Changes to this Privacy Policy',
        'Contact Us',
      ]}
    >

      <PolicySection title="Interpretation and Definitions">
        <PolicyHeading>Interpretation</PolicyHeading>
        <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

        <PolicyHeading>Definitions</PolicyHeading>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Buggy Basket, Thurso KW14.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: United Kingdom</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong>Website</strong> refers to Buggy Basket, accessible from <a href="https://www.buggybasket.com" target="_blank" rel="noopener noreferrer">https://www.buggybasket.com</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service.</li>
        </ul>
      </PolicySection>

      <PolicySection title="Collecting and Using Your Personal Data">
        <PolicyHeading>Types of Data Collected</PolicyHeading>
        <PolicySubHeading>Personal Data</PolicySubHeading>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information. This may include, but is not limited to:</p>
        <ul>
          <li>Email address</li>
        </ul>

        <PolicySubHeading>Usage Data</PolicySubHeading>
        <p>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, and other diagnostic data.</p>

        <PolicySubHeading>Tracking Technologies and Cookies</PolicySubHeading>
        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
        <ul>
          <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
          <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email.</li>
        </ul>
        <p>Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool or through Your browser settings.</p>
        <ul>
          <li><strong>Necessary / Essential Cookies</strong> — These Cookies are essential to provide You with services available through the Website.</li>
          <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — These Cookies identify if users have accepted the use of cookies on the Website.</li>
          <li><strong>Functionality Cookies</strong> — These Cookies allow Us to remember choices You make when You use the Website.</li>
        </ul>

        <PolicyHeading>Use of Your Personal Data</PolicyHeading>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
          <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract.</li>
          <li><strong>To contact You</strong> regarding updates or informative communications related to the functionalities, products or contracted services.</li>
          <li><strong>To provide You</strong> with news, special offers, and general information about other goods and services.</li>
          <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
          <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, or other sale or transfer of some or all of Our assets.</li>
          <li><strong>For other purposes</strong> such as data analysis, identifying usage trends, and evaluating and improving our Service.</li>
        </ul>

        <PolicyHeading>Retention of Your Personal Data</PolicyHeading>
        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Retention periods include:</p>
        <ul>
          <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
          <li><strong>Support tickets and correspondence:</strong> up to 24 months from the date of ticket closure.</li>
          <li><strong>Website analytics data:</strong> up to 24 months from the date of collection.</li>
          <li><strong>Server logs:</strong> up to 24 months for security monitoring and troubleshooting purposes.</li>
        </ul>

        <PolicyHeading>Transfer of Your Personal Data</PolicyHeading>
        <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>

        <PolicyHeading>Delete Your Personal Data</PolicyHeading>
        <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section.</p>
      </PolicySection>

      <PolicySection title="Disclosure of Your Personal Data">
        <PolicyHeading>Business Transactions</PolicyHeading>
        <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

        <PolicyHeading>Law Enforcement</PolicyHeading>
        <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

        <PolicyHeading>Other Legal Requirements</PolicyHeading>
        <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
      </PolicySection>

      <PolicySection title="Security of Your Personal Data">
        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
      </PolicySection>

      <PolicySection title="Children's Privacy">
        <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
      </PolicySection>

      <PolicySection title="Links to Other Websites">
        <p>Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
      </PolicySection>

      <PolicySection title="Changes to this Privacy Policy">
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
      </PolicySection>

      <PolicySection title="Contact Us">
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul>
          <li>By email: <a href="mailto:buggybasket@gmail.com">buggybasket@gmail.com</a></li>
        </ul>
      </PolicySection>

    </PolicyLayout>
  );
}