import { PolicyLayout, PolicySection, PolicyHeading } from '../components/PolicyComponents';

export const metadata = {
  title: 'Refunds & Returns — Buggy Basket',
  description: 'Refunds and Returns Policy for Buggy Basket.',
};

export default function RefundsPage() {
  return (
    <PolicyLayout
      title="Refunds & Returns"
      lastUpdated="March 29, 2026"
      warning="This is a draft Refunds & Returns policy generated by FreePrivacyPolicy. Please review and replace with final legal text approved by the team/lawyer before going live."
      tocItems={[
        'Interpretation and Definitions',
        'Your Order Cancellation Rights',
        'Conditions for Returns',
        'Returning Goods',
        'Gifts',
        'Contact Us',
      ]}
    >

      <PolicySection title="Interpretation and Definitions">
        <PolicyHeading>Interpretation</PolicyHeading>
        <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

        <PolicyHeading>Definitions</PolicyHeading>
        <p>For the purposes of this Return and Refund Policy:</p>
        <ul>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Policy) refers to Buggy Basket, Thurso, Scotland, UK.</li>
          <li><strong>Goods</strong> refer to the items offered for sale on the Service.</li>
          <li><strong>Orders</strong> mean a request by You to purchase Goods from Us.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Website</strong> refers to Buggy Basket, accessible from <a href="https://www.buggybasket.com" target="_blank" rel="noopener noreferrer">https://www.buggybasket.com</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>
      </PolicySection>

      <PolicySection title="Your Order Cancellation Rights">
        <p>You are entitled to cancel Your Order within 14 days without giving any reason for doing so.</p>
        <p>The deadline for cancelling an Order is 14 days from the date on which You received the Goods or on which a third party you have appointed, who is not the carrier, takes possession of the product delivered.</p>
        <p>In order to exercise Your right of cancellation, You must inform Us of your decision by means of a clear statement. You can inform Us of your decision by:</p>
        <ul>
          <li>By email: <a href="mailto:buggybasket@gmail.com">buggybasket@gmail.com</a></li>
          <li>By phone: <a href="tel:07442138532">07442138532</a></li>
        </ul>
        <p>We will reimburse You no later than 14 days from the day on which We receive the returned Goods. We will use the same means of payment as You used for the Order, and You will not incur any fees for such reimbursement.</p>
      </PolicySection>

      <PolicySection title="Conditions for Returns">
        <p>In order for the Goods to be eligible for a return, please make sure that:</p>
        <ul>
          <li>The Goods were purchased in the last 14 days</li>
          <li>The Goods are in the original packaging</li>
        </ul>
        <p>The following Goods cannot be returned:</p>
        <ul>
          <li>The supply of Goods made to Your specifications or clearly personalized.</li>
          <li>The supply of Goods which according to their nature are not suitable to be returned, deteriorate rapidly or where the date of expiry is over.</li>
          <li>The supply of Goods which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery.</li>
          <li>The supply of Goods which are, after delivery, according to their nature, inseparably mixed with other items.</li>
        </ul>
        <p>We may refuse returns that do not meet the conditions above, to the extent permitted by applicable law.</p>
        <p>Only regular priced Goods may be refunded. Unfortunately, Goods on sale cannot be refunded. This exclusion may not apply to You if it is not permitted by applicable law.</p>
      </PolicySection>

      <PolicySection title="Returning Goods">
        <p>You are responsible for the cost and risk of returning the Goods to Us. You should send the Goods to the following address:</p>
        <p><strong>Thurso, Scotland, UK</strong></p>
        <p>We cannot be held responsible for Goods damaged or lost in return shipment. Therefore, We recommend an insured and trackable mail service. We are unable to issue a refund without actual receipt of the Goods or proof of received return delivery.</p>
      </PolicySection>

      <PolicySection title="Gifts">
        <p>If the Goods were marked as a gift when purchased and then shipped directly to you, You&apos;ll receive a gift credit for the value of your return. Once the returned product is received, a gift certificate will be mailed to You.</p>
        <p>If the Goods weren&apos;t marked as a gift when purchased, or the gift giver had the Order shipped to themselves to give it to You later, We will send the refund to the gift giver.</p>
      </PolicySection>

      <PolicySection title="Contact Us">
        <p>If you have any questions about our Returns and Refunds Policy, please contact us:</p>
        <ul>
          <li>By email: <a href="mailto:buggybasket@gmail.com">buggybasket@gmail.com</a></li>
          <li>By phone: <a href="tel:07442138532">07442138532</a></li>
        </ul>
      </PolicySection>

    </PolicyLayout>
  );
}